export const UPDATE_PATIENTS = "UPDATE_PATIENTS";
export const UPDATE_CURRENT_PATIENT = "UPDATE_CURRENT_PATIENT";

export const UPDATE_CLIENTS = "UPDATE_CLIENTS";

export const UPDATE_CURRENT_CLIENT = "UPDATE_CURRENT_CLIENT";

export const REMOVE_PRESCRIPTION = "REMOVE_PRESCRIPTION";

// export const DOSAGE_CHECKED = "DOSAGE_CHECKED"